#!/usr/bin/env python3
"""Grounded outdoor meshes; existing scene materials and optical geometry are retained."""
import argparse
from array import array
from bisect import bisect_right
import json
import math
from pathlib import Path
import random
import re
import subprocess

from build_scene_models import Mesh, add, sub, mul, norm, cross, TAU, ROOT

OUT=ROOT/'models'/'landscapes'
CACHE=ROOT/'out'/'landscape-authoring'


def smooth(a,b,x):
    t=max(0,min(1,(x-a)/(b-a)))
    return t*t*(3-2*t)


def noise(x,y):
    # Continuous multi-scale relief, deliberately small relative to the existing mountains.
    return (.5+.22*math.sin(x*.19+math.sin(y*.21))+.17*math.sin(y*.37+x*.07)
            +.08*math.sin(x*1.13-y*.71)+.025*math.sin(x*4.71+y*3.17))


class Terrain:
    def __init__(self,scene):
        self.scene=scene
        prefix=CACHE/scene
        subprocess.run([str(ROOT/'build'/'sample_landscape'),str(ROOT/'scenes'/(scene+'.owe')),str(prefix)],check=True)
        meta=json.loads(prefix.with_suffix('.json').read_text())
        self.n=meta['resolution'];self.sx,self.sy=meta['size'];self.base=meta['origin_height']
        self.heights=array('d')
        with prefix.with_suffix('.heights').open('rb') as f:
            self.heights.fromfile(f,(self.n+1)**2)

    def support(self,x,y):
        # Exact interpolation of the original terrain triangles, not a second noise implementation.
        u=max(0,min(self.n-1e-9,(x/self.sx+.5)*self.n))
        v=max(0,min(self.n-1e-9,(y/self.sy+.5)*self.n))
        i,j=int(u),int(v);u-=i;v-=j;k=j*(self.n+1)+i
        a,b,c,d=(self.heights[k],self.heights[k+1],self.heights[k+self.n+2],self.heights[k+self.n+1])
        return a+(b-a)*u+(c-b)*v if u>=v else a+(c-d)*u+(d-a)*v

    def protected(self,x,y):
        if self.scene=='the_temple':
            return smooth(0,2,max(abs(x)-22,-12-y,y-48))
        r=math.hypot(x,y)
        if self.scene=='the_observatory':return smooth(10,15,r)
        return smooth(3,7,r)*smooth(13,20,math.hypot(x-450,y))

    def smooth_support(self,x,y):
        # Bicubic reconstruction removes the old grid's abrupt normal changes.
        u=(x/self.sx+.5)*self.n;v=(y/self.sy+.5)*self.n;i=math.floor(u);j=math.floor(v)
        def cubic(a,b,c,d,t):return .5*(2*b+(-a+c)*t+(2*a-5*b+4*c-d)*t*t+(-a+3*b-3*c+d)*t*t*t)
        rows=[]
        for yy in range(j-1,j+3):
            row=[self.heights[max(0,min(self.n,yy))*(self.n+1)+max(0,min(self.n,xx))] for xx in range(i-1,i+3)]
            rows.append(cubic(*row,u-i))
        return cubic(*rows,v-j)

    def raw_height(self,x,y):
        edge=smooth(0,20,min(self.sx/2-abs(x),self.sy/2-abs(y)))
        amount=.27 if self.scene=='the_telescope' else .16
        factor=self.protected(x,y)*edge
        base=self.support(x,y)
        relief=(.012+amount*max(0,noise(x,y)))
        return base+factor*(self.smooth_support(x,y)-base+relief)

    def height(self,x,y):
        if not hasattr(self,'surface_mesh'):return self.raw_height(x,y)
        i=max(0,min(len(self.xs)-2,bisect_right(self.xs,x)-1))
        j=max(0,min(len(self.ys)-2,bisect_right(self.ys,y)-1))
        u=(x-self.xs[i])/(self.xs[i+1]-self.xs[i]);v=(y-self.ys[j])/(self.ys[j+1]-self.ys[j])
        w=len(self.xs);k=j*w+i;p=self.surface_mesh.vertices
        a,b,c,d=p[k][2],p[k+1][2],p[k+w+1][2],p[k+w][2]
        return a+(b-a)*u+(c-b)*v if u>=v else a+(c-d)*u+(d-a)*v

    def slope(self,x,y):
        return math.hypot(self.support(x+1,y)-self.support(x-1,y),self.support(x,y+1)-self.support(x,y-1))/2


class Landscape:
    def __init__(self,scene):
        self.scene=scene;self.terrain=Terrain(scene);self.meshes={};self.materials={};self.roots=[]

    def part(self,name,material):
        self.materials[name]=material
        return self.meshes.setdefault(name,Mesh())

    def save(self):
        OUT.mkdir(parents=True,exist_ok=True)
        lines=['# BEGIN LANDSCAPE MODELS','# Generated by tools/build_landscapes.py; existing materials, metres, world coordinates.']
        for name,mesh in self.meshes.items():
            if not mesh.faces:continue
            filename=self.scene+'_'+name+'.obj';mesh.write(OUT/filename)
            # Separate flat ground from its index-matched reference boundary;
            # coincident transmissive/opaque hits could skip the visible sheet.
            # Terrain, rock and plants are curved surfaces: smooth shading normals (edges sharper
            # than the default 30° crease, such as rock fractures, stay sharp).
            lines.append(f'body Landscape_{name} {{ type = mesh file = "../models/landscapes/{filename}" material = {self.materials[name]} normals = smooth position = (0, 0, 0.0005) }}')
            print(f'{self.scene}/{name}: {len(mesh.faces):,} triangles',flush=True)
        lines.append('# END LANDSCAPE MODELS')
        path=ROOT/'scenes'/(self.scene+'.owe');source=path.read_text()
        block='\n'.join(lines)
        if '# BEGIN LANDSCAPE MODELS' in source:
            source=re.sub(r'# BEGIN LANDSCAPE MODELS.*?# END LANDSCAPE MODELS',lambda _:block,source,flags=re.S)
        else:
            source=source.replace('# END CRAFTED MODELS','# END CRAFTED MODELS\n\n'+block)
        if self.scene=='the_telescope':
            source=re.sub(r'body Woods\s*\{[^}]*\}', '# Woods replaced by terrain-grounded branching conifers below.',source)
            source=re.sub(r'# BEGIN CRAFTED MODELS.*?# END CRAFTED MODELS',
                          '# BEGIN CRAFTED MODELS\n# Foreground models are now generated with the landscape.\n# END CRAFTED MODELS',source,flags=re.S)
        # Keep Ground as the original on_terrain coordinate reference, without matter:
        # a reference-only terrain adds no surface that could overlap the visible relief.
        # The replacement mesh retains the original terrain's visible material.
        source=re.sub(r'(body Ground\s*\{[^}]*?)(?:material|medium)\s*=\s*\w+',r'\1reference_only = true',source)
        source=source.replace('material Landscape_coordinate_reference { type = null }\n','')
        if '# Coordinate-only terrain' not in source:
            source=source.replace('body Ground {','# Coordinate-only terrain (heights for on_terrain, no matter); the visible ground is Landscape_Ground_relief.\nbody Ground {')
        path.write_text(source)
        (OUT/(self.scene+'.placement.json')).write_text(json.dumps(self.roots,indent=2))


def graded_axis(extent,near=70):
    values=[0.]
    for end,step in ((near,.65),(280,2.8),(extent,7.)):
        end=min(end,extent)
        while values[-1]<end-1e-8:values.append(min(end,values[-1]+step))
    return [-v for v in reversed(values[1:])]+values


def ground(model,material):
    mesh=model.part('Ground_relief',material);t=model.terrain
    xs=graded_axis(t.sx/2);ys=graded_axis(t.sy/2);w=len(xs)
    mesh.vertices=[(x,y,t.raw_height(x,y)) for y in ys for x in xs]
    for j in range(len(ys)-1):
        for i in range(w-1):
            k=j*w+i
            mesh.faces.extend(((k,k+1,k+w+1),(k,k+w+1,k+w)))
    t.xs=xs;t.ys=ys;t.surface_mesh=mesh


def rock(mesh,center,scale,rng,angle=0):
    """Buried, closed, fractured boulder with non-boxy planar strata."""
    sx,sy,sz=scale;phase=rng.uniform(0,TAU);rings=[];N=13
    radial=[rng.uniform(.78,1.18) for _ in range(N)]
    for row,(z,r) in enumerate(((-.28,.70),(.04,1),(.38,.91),(.76,.64),(.96,.24))):
        points=[]
        for i in range(N):
            a=i*TAU/N;rr=radial[i]*(r+.055*math.sin(i*2.1+row+phase))
            x=sx*rr*math.cos(a)+sx*z*.14;y=sy*rr*math.sin(a)
            points.append(add(center,(x*math.cos(angle)-y*math.sin(angle),x*math.sin(angle)+y*math.cos(angle),sz*(z+rng.uniform(-.07,.07)))))
        rings.append(points)
    mesh.polygon(list(reversed(rings[0])))
    for a,b in zip(rings,rings[1:]):
        for k in range(N):mesh.polygon([a[k],a[(k+1)%N],b[(k+1)%N],b[k]])
    mesh.polygon(rings[-1])


def grass(mesh,root,rng,height):
    for blade in range(rng.randint(6,11)):
        a=rng.random()*TAU;h=height*rng.uniform(.45,1.25);bend=rng.uniform(.25,.75)*h
        width=rng.uniform(.002,.005);side=(-math.sin(a)*width,math.cos(a)*width,0)
        p=add(root,(rng.uniform(-.025,.025),rng.uniform(-.025,.025),0))
        mid=add(p,(bend*.35*math.cos(a),bend*.35*math.sin(a),h*.62));tip=add(p,(bend*math.cos(a),bend*math.sin(a),h))
        mesh.polygon([sub(p,side),add(p,side),add(mid,mul(side,.6)),sub(mid,mul(side,.6))])
        mesh.polygon([sub(mid,mul(side,.6)),add(mid,mul(side,.6)),tip])


def feather(mesh,start,end,width,rng,teeth=7,tilt=None):
    """Folded, serrated branch spray: geometry with open spaces, never a solid cone."""
    axis=sub(end,start);side=norm(cross(axis,(0,0,1)));normal=norm(cross(axis,side))
    angle=rng.uniform(-1.15,1.15) if tilt is None else tilt
    side=add(mul(side,math.cos(angle)),mul(normal,math.sin(angle)))
    for sign in (-1,1):
        for i in range(teeth):
            u=i/teeth;v=(i+1)/teeth
            a=add(start,mul(axis,u));b=add(start,mul(axis,v))
            spread=width*math.sin(math.pi*(u*.85+.07))*rng.uniform(.65,1.2)
            tip=add(add(start,mul(axis,u+.16)),add(mul(side,spread*sign),mul(normal,spread*.22)))
            mesh.polygon([a,tip,b])


def conifer(model,x,y,height,seed,detail):
    rng=random.Random(seed);z=model.terrain.height(x,y)-.08
    trunk=model.part('Conifer_bark','bark');leaves=model.part('Conifer_sprays','needles')
    lean=(rng.uniform(-.025,.025)*height,rng.uniform(-.025,.025)*height)
    p=[(x+lean[0]*u*u,y+lean[1]*u*u,z+height*u) for u in (0,.2,.45,.7,1)]
    trunk.wood_branch(p,[height*r for r in (.014,.010,.006,.003,.0005)],10 if detail else 7)
    levels=22 if detail==2 else (16 if detail==1 else 10)
    wide=rng.uniform(.17,.24);phase=rng.random()*TAU
    for layer in range(levels):
        u=.10+layer*.88/levels;root=(x+lean[0]*u*u,y+lean[1]*u*u,z+height*u)
        count=rng.randint(4,7)
        for branch in range(count):
            root=(x+lean[0]*u*u,y+lean[1]*u*u,z+height*(u+rng.uniform(-.35,.35)/levels))
            a=branch*TAU/count+layer*2.399+phase+rng.uniform(-.2,.2)
            reach=height*wide*(1-u)**.85*rng.uniform(.65,1.12)
            elbow=add(root,(math.cos(a)*reach*.55,math.sin(a)*reach*.55,-reach*.21))
            end=add(root,(math.cos(a)*reach,math.sin(a)*reach,-reach*.07))
            if detail:trunk.branch([root,elbow,end],[height*.0017,.009,.0015],5)
            # Overlapping, folded secondary branchlets give the crown volume
            # from the side as well as above; avoid the bare horizontal-tier silhouette.
            for bank in (-1,1):
                start=add(mul(root,.72),mul(elbow,.28))
                tip=add(end,(0,0,reach*.22))
                feather(leaves,start,tip,reach*.28,rng,11 if detail else 7,bank*.82)
            shoots=7 if detail==2 else (5 if detail==1 else 3)
            for shoot in range(shoots):
                t=.22+shoot*.76/shoots;c=add(mul(root,1-t),mul(end,t))
                c=add(c,(0,0,-reach*.18*math.sin(math.pi*t)))
                for sign in (-1,1):
                    aa=a+sign*rng.uniform(.45,1.0)
                    length=max(.16,reach*(.36-.20*t))*rng.uniform(.8,1.2)
                    tip=add(c,(math.cos(aa)*length,math.sin(aa)*length,length*rng.uniform(.3,.85)))
                    feather(leaves,c,tip,length*.40,rng,8 if detail==2 else 5)
                    if detail==2:
                        # A second folded spray exposes needles when viewed edge-on.
                        feather(leaves,add(c,(0,0,.025)),add(tip,(0,0,length*.2)),length*.24,rng,7)
    model.roots.append(dict(kind='tree',position=[x,y,z],surface=model.terrain.height(x,y),height=height,detail=detail))


def alpine(model):
    t=model.terrain;rng=random.Random(58107)
    stone=model.part('Fractured_granite','granite');herbs=model.part('Alpine_tussocks','needles')
    # Geologically related clusters, with smaller scree accumulating around outcrops.
    clusters=[(rng.uniform(-170,650),rng.choice((-1,1))*rng.uniform(12,180)) for _ in range(42)]
    for cx,cy in clusters:
        for k in range(rng.randint(7,15)):
            x=cx+rng.gauss(0,5);y=cy+rng.gauss(0,4)
            if math.hypot(x,y)<6 or math.hypot(x-450,y)<15:continue
            size=rng.uniform(.3,2.4)*(1.6 if k==0 else 1)
            rock(stone,(x,y,t.height(x,y)-size*.12),(size,size*.68,size*.74),rng,.4+rng.uniform(-.28,.28))
    for k in range(1100):
        x=rng.uniform(-48,65);y=rng.uniform(-48,48)
        if math.hypot(x,y)<2.6:continue
        size=rng.uniform(.025,.19)
        rock(stone,(x,y,t.height(x,y)-size*.15),(size,size*.75,size*.5),rng,rng.random()*TAU)
    for k in range(10000):
        x=rng.uniform(-90,115);y=rng.uniform(-90,90)
        if math.hypot(x,y)<2.2 or noise(x*.42,y*.42)<.41:continue
        grass(herbs,(x,y,t.height(x,y)+.002),rng,rng.uniform(.10,.38))
    centers=[(rng.uniform(-700,1150),rng.uniform(-1000,1000)) for _ in range(24)]
    candidates=[(rng.uniform(-110,170),rng.uniform(-140,140)) for _ in range(110)]
    candidates += [(cx+rng.gauss(0,65),cy+rng.gauss(0,65)) for cx,cy in centers for _ in range(24)]
    accepted=[]
    for x,y in candidates:
        r=math.hypot(x,y)
        # Preserve a generous corridor to the optical demonstration's target statue.
        if r<16 or (-10<x<495 and abs(y)<16) or math.hypot(x-450,y)<28:continue
        if t.slope(x,y)>.85 or t.support(x,y)>t.base+165:continue
        if any((x-a)**2+(y-b)**2<36 for a,b in accepted):continue
        accepted.append((x,y));detail=2 if r<95 else (1 if r<320 else 0)
        conifer(model,x,y,rng.uniform(6,19)*(1 if r<320 else 1.3),58100+len(accepted),detail)
    print(f'Alpine woodland: {len(accepted)} slope-grounded trees',flush=True)


def mediterranean(model):
    t=model.terrain;rng=random.Random(7418)
    stone=model.part('Limestone_outcrops','hillside');herbs=model.part('Dry_tussocks','olive')
    # A broken rocky verge softens the precinct's hard rectangular edge.
    for k in range(950):
        side=rng.randrange(4)
        if side<2:x=rng.choice((-1,1))*rng.uniform(22.1,39);y=rng.uniform(-22,57)
        else:x=rng.uniform(-35,35);y=rng.uniform(-25,-12.2) if side==2 else rng.uniform(48.2,60)
        if abs(x)<3 and y<0:continue  # keep the approach readable
        size=rng.uniform(.035,.40)
        if k%29==0:size=rng.uniform(.8,1.8)
        rock(stone,(x,y,t.height(x,y)-size*.12),(size,size*.6,size*.5),rng,.25+rng.uniform(-.35,.35))
    for k in range(12000):
        x=rng.uniform(-47,47);y=rng.uniform(-30,68)
        if -22.1<x<22.1 and -12.1<y<48.1:continue
        if abs(x)<2.4 and y<0 or noise(x*.6,y*.6)<.4:continue
        grass(herbs,(x,y,t.height(x,y)+.002),rng,rng.uniform(.12,.45))
    for k in range(140):
        x=rng.uniform(-130,130);y=rng.uniform(-65,150)
        if -42<x<42 and -32<y<72:continue
        size=rng.uniform(.7,3.2)
        rock(stone,(x,y,t.height(x,y)-size*.2),(size*1.4,size*.7,size*.62),rng,.3)


def observatory(model):
    t=model.terrain;rng=random.Random(2352);stone=model.part('Hillside_outcrops','rock')
    for k in range(520):
        a=rng.random()*TAU;r=rng.uniform(12,110);x=r*math.cos(a);y=r*math.sin(a)
        if abs(x)<2.2 and y<0:continue
        size=rng.uniform(.08,1.6)
        rock(stone,(x,y,t.height(x,y)-size*.15),(size,size*.63,size*.58),rng,.8+rng.uniform(-.2,.2))


def build(scene):
    model=Landscape(scene)
    ground(model,{'the_telescope':'alpine','the_temple':'hillside','the_observatory':'rock'}[scene])
    {'the_telescope':alpine,'the_temple':mediterranean,'the_observatory':observatory}[scene](model)
    model.save()


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('scene',nargs='?',default='all',choices=('all','telescope','temple','observatory'))
    args=parser.parse_args()
    # The terrain sampler is a CMake target of the engine (built on demand, kept up to date by CMake).
    subprocess.run(['cmake','--build','build','--target','sample_landscape'],cwd=ROOT,check=True)
    for name in ('telescope','temple','observatory') if args.scene=='all' else (args.scene,):build('the_'+name)
